#!/bin/bash
# Strip the binaries Mesa has already built, keeping everything needed to
# relink and to keep rebuilding.
#
# Mesa's build output lives in build/mesa (the Meson build dir); the vendored
# source in mesa/ only ever collects build byproducts (the __pycache__ dirs the
# Python code generators leave behind). So the bulk of the reclaimable space is
# the intermediate objects and build-tree archives under build/mesa/src.
#
# What is kept, because jtl and `make mesa` need it:
#   build/mesa/prefix/          the installed static libs the jtl link reads
#                               (libEGL.a, libgbm.a, libGLESv2.a,
#                               libgallium-*.a, lib/gbm/dri_gbm.a) plus their
#                               headers and .pc files
#   build/mesa/build.ninja      the build graph, so a later rebuild is
#   build/mesa/meson-private/   incremental instead of a full reconfigure
#   mesa/                       all sources - only byproducts are removed there
#
# Deleting the intermediates is safe: `make mesa` re-runs the compiler over the
# sources and regenerates every archive, and the jtl link is unaffected because
# it reads the installed prefix, not build/mesa/src.
#
# Usage:
#   ./trim-mesa.sh              strip intermediates, keep the installed prefix
#   ./trim-mesa.sh --dry-run    list what would go, delete nothing
#   ./trim-mesa.sh --generated  also drop generated .c/.h in build/mesa/src
#                               (regenerated by the Python code generators)
#   ./trim-mesa.sh --src-only   only clean the mesa/ source tree

set -e
cd "$(dirname "$0")"

MESA_DIR=mesa
MESA_BUILD=build/mesa

DRY_RUN=0
GENERATED=0
SRC_ONLY=0

usage() {
	sed -n '2,28{s/^# \{0,1\}//;p;}' "$0"
}

while [ $# -gt 0 ]; do
	case "$1" in
	-n | --dry-run) DRY_RUN=1 ;;
	--generated) GENERATED=1 ;;
	--src-only) SRC_ONLY=1 ;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "unknown option: $1 (try --help)" >&2
		exit 1
		;;
	esac
	shift
done

if [ "$DRY_RUN" -eq 1 ]; then
	echo "(dry run: nothing is deleted)"
fi

# Counts matches, or removes them when not in dry-run mode.
#
# The trailing -print / -exec is required: with no explicit action, find appends
# an implicit -print to the whole expression, which would also fire on the
# branch matched by -prune and report the pruned directory itself as a match.
# Removal uses -exec rm rather than -delete, since -delete implies -depth and
# would turn the -prune protecting build/mesa/prefix into a no-op.
sweep() {
	local label="$1"
	shift
	local n
	n=$(find "$@" -print 2>/dev/null | wc -l)
	if [ "$n" -eq 0 ]; then
		return
	fi
	echo "  $label: $n file(s)"
	[ "$DRY_RUN" -eq 1 ] || find "$@" -exec rm -rf {} + 2>/dev/null || true
}

# ---- vendored source tree: byproducts only, sources stay ----
if [ -d "$MESA_DIR" ]; then
	echo "== trim: $MESA_DIR (source tree, byproducts only) =="
	sweep "python bytecode dirs" "$MESA_DIR" -type d -name '__pycache__'
	sweep "stray objects/archives" "$MESA_DIR" -type f \
		\( -name '*.o' -o -name '*.a' -o -name '*.so' -o -name '*.so.*' \
		-o -name '*.rlib' -o -name '*.pyc' -o -name '*.pyo' \)
	echo "  remaining: $(du -sh "$MESA_DIR" | cut -f1)"
else
	echo "skipping $MESA_DIR (not present)"
fi

if [ "$SRC_ONLY" -eq 1 ]; then
	echo "== done (source tree only) =="
	exit 0
fi

# ---- meson build tree: intermediates only ----
if [ ! -d "$MESA_BUILD" ]; then
	echo "skipping $MESA_BUILD (not present)"
	echo "== done =="
	exit 0
fi

echo "== trim: $MESA_BUILD (build tree, intermediates only) =="

# build/mesa/prefix is the installed tree the jtl link reads, so it is pruned
# out before any of these sweeps.
PRUNE=(-path "$MESA_BUILD/prefix" -prune -o)

sweep "intermediate objects" "$MESA_BUILD" "${PRUNE[@]}" \
	-type f -name '*.o'
sweep "build-tree archives" "$MESA_BUILD" "${PRUNE[@]}" \
	-type f -name '*.a'
sweep "shared objects" "$MESA_BUILD" "${PRUNE[@]}" \
	-type f \( -name '*.so' -o -name '*.so.*' \)

if [ "$GENERATED" -eq 1 ]; then
	echo "  dropping generated sources in $MESA_BUILD/src (ninja regenerates)"
	sweep "generated sources" "$MESA_BUILD/src" -type f \
		\( -name '*.c' -o -name '*.cpp' -o -name '*.h' \)
fi

# build.ninja, meson-private/ and the generated headers all stay, so the next
# `make mesa` is incremental rather than a full reconfigure.
echo "  remaining: $(du -sh "$MESA_BUILD" | cut -f1)"

echo "== sanity checks =="
check() {
	if [ -e "$1" ]; then
		echo "  ok: $1"
	else
		echo "  MISSING: $1"
		exit 1
	fi
}
check "$MESA_DIR/meson.build"
check "$MESA_BUILD/build.ninja"
check "$MESA_BUILD/prefix/lib/libEGL.a"
check "$MESA_BUILD/prefix/lib/libgbm.a"
check "$MESA_BUILD/prefix/lib/libGLESv2.a"
check "$MESA_BUILD/prefix/lib/gbm/dri_gbm.a"

echo "Done."